[project]
name = "jac-tutorials"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jaclang>=0.8.7",
    "jaseci>=1.4.2.6",
]
